/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PopupMenu;

import Database.Database;
import Entitas.Kamar;
import Entitas.Pemesanan;
import Entitas.Tamu;
import Kontrol.KamarKontrol;
import Kontrol.PemesananKontrol;
import Kontrol.TamuKontrol;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.time.ZoneId;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

public class PopupTambahEditPemesanan extends javax.swing.JDialog implements PopupMenu{
    //Variable Global
    private Database database;
    
    private TamuKontrol tamuKontrol;
    private KamarKontrol kamarKontrol;
    private PemesananKontrol pemesananKontrol;
    
    private DefaultListModel<String> listKamarKosong;
    
    private Tamu tamu;
    private Kamar kamar;
    
    private int idxRow;
    
    //Prosedur load 3 databse
    public void loadDatabase() throws IOException{
        database = new Database();
        database.memuatDatabase();
        
        tamuKontrol = database.getTamuKontrol();
        kamarKontrol = database.getKamarKontrol();
        pemesananKontrol = database.getPemesananKontrol();
    }
    
    //Prosedur nampilin list kamar kosong
    private void setList(){
        listKamarKosong = new  DefaultListModel<String>();
        for (int i = 0; i < kamarKontrol.sizeData(); i++) {
            if(kamarKontrol.listKamar().get(i).isStatusKamar() == false){
                listKamarKosong.addElement(kamarKontrol.listKamar().get(i).getNomorKamar());
            }
            
        }
        
        List_KamarKosong.setModel(listKamarKosong);
        
        
        DatePicker_CheckIn.setFormats(new String[]{"dd MMMM yyyy"});
        DatePicker_CheckOut.setFormats(new String[]{"dd MMMM yyyy"});
    }
    
    public void setFieldEdit(){
        Pemesanan pemesanan = pemesananKontrol.listPemesanan().get(idxRow);
            
        //update status menjadi terisi
        int locPemesananUpdate = kamarKontrol.getLoc(pemesanan.getKamar());
        kamarKontrol.updateStatusKamar(locPemesananUpdate, false);
        
        //Isi field nama
        Field_CariNamaNO.setText(pemesanan.getTamu().getNamaTamu());
        Button_CariTamu.doClick();
        
        //Isi field Pilih kamar
        setList();
        String noKamar = pemesanan.getKamar().getNomorKamar();  
        Object objNoKamar = noKamar;
        List_KamarKosong.setSelectedValue(objNoKamar, true);
        Button_PilihKamar.doClick();
        
        //isi field waktu penginapan dengan convert localdate ke date
        Date checkIn = Date.from(pemesanan.getWaktuCheckIn().atStartOfDay(ZoneId.systemDefault()).toInstant());
        Date checkOut = Date.from(pemesanan.getWaktuCheckOut().atStartOfDay(ZoneId.systemDefault()).toInstant());
        DatePicker_CheckIn.setDate(checkIn);
        DatePicker_CheckOut.setDate(checkOut);
        Button_HitungHarga.doClick();
        
        //isiPembayaran
        Object obj;
        if(pemesanan.isPembayaran() == true){
            String s = "Cash";  
            obj = s;
        }else{
            String s = "Kredit";  
            obj = s;
        }
        
        ComboBox_Pembayaran.setSelectedItem(obj);
    }
    
    /**
     * Creates new form PopupTambahEditPemesanan
     */
    public PopupTambahEditPemesanan(java.awt.Frame parent, boolean modal, int idxRow) {
        super(parent, modal);
        
        //Load database
        try {
            loadDatabase();
        } catch (IOException ex) {
            Logger.getLogger(PopupTambahEditTamu.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Set id row menjadi variabel global
        this.idxRow = idxRow;
        
        initComponents();
        //nampilin list
        setList();
        if(idxRow != -1){
            setFieldEdit();
            Button_PesanKamar.setText("Update pesan kamar");
        }
    }

    PopupTambahEditPemesanan() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Field_CariNamaNO = new javax.swing.JTextField();
        Label_NamaTamu = new javax.swing.JLabel();
        Button_CariTamu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        List_KamarKosong = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Button_PilihKamar = new javax.swing.JButton();
        Label_HargaPerMalam = new javax.swing.JLabel();
        Label_Rating = new javax.swing.JLabel();
        Label_StatusWifi = new javax.swing.JLabel();
        Label_TipeKamar = new javax.swing.JLabel();
        Label_KamarTerpilih = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DatePicker_CheckIn = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        DatePicker_CheckOut = new org.jdesktop.swingx.JXDatePicker();
        Button_HitungHarga = new javax.swing.JButton();
        Label_Harga = new javax.swing.JLabel();
        Button_PesanKamar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ComboBox_Pembayaran = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Cari nama atau nomor telepon tamu pemesan");

        Field_CariNamaNO.setName(""); // NOI18N
        Field_CariNamaNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_CariNamaNOActionPerformed(evt);
            }
        });

        Button_CariTamu.setText("Cari");
        Button_CariTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CariTamuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Field_CariNamaNO)
                .addGap(18, 18, 18)
                .addComponent(Button_CariTamu))
            .addComponent(Label_NamaTamu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Field_CariNamaNO, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_CariTamu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_NamaTamu))
        );

        Field_CariNamaNO.getAccessibleContext().setAccessibleName("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Pilih kamar");

        List_KamarKosong.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        List_KamarKosong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                List_KamarKosongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(List_KamarKosong);

        jLabel2.setText("Tipe kamar ");

        jLabel9.setText("Status Wi-Fi");

        jLabel11.setText("Rating");

        jLabel4.setText("Harga");

        Button_PilihKamar.setText("Pilih kamar");
        Button_PilihKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PilihKamarActionPerformed(evt);
            }
        });

        Label_HargaPerMalam.setText(": Rp-/malam");

        Label_Rating.setText(": -");

        Label_StatusWifi.setText(": -");

        Label_TipeKamar.setText(": -");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(16, 16, 16))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Label_KamarTerpilih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Label_Rating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label_TipeKamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label_StatusWifi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label_HargaPerMalam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(Button_PilihKamar)
                            .addGap(0, 0, Short.MAX_VALUE)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Label_TipeKamar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Label_StatusWifi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Label_Rating))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Label_HargaPerMalam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_PilihKamar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_KamarTerpilih)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Set waktu check in dan check out");

        jLabel5.setText("Check in");

        DatePicker_CheckIn.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                DatePicker_CheckInPopupMenuWillBecomeVisible(evt);
            }
        });

        jLabel6.setText("Check out");

        DatePicker_CheckOut.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                DatePicker_CheckOutPopupMenuWillBecomeVisible(evt);
            }
        });

        Button_HitungHarga.setText("Hitung harga");
        Button_HitungHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_HitungHargaActionPerformed(evt);
            }
        });

        Label_Harga.setText("Harga total: Belum dihitung");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(DatePicker_CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DatePicker_CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(Button_HitungHarga)
                    .addComponent(Label_Harga))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DatePicker_CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DatePicker_CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_HitungHarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Harga))
        );

        Button_PesanKamar.setText("Pesan kamar");
        Button_PesanKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PesanKamarActionPerformed(evt);
            }
        });

        jLabel8.setText("Pembayaran");

        ComboBox_Pembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Kredit" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox_Pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_PesanKamar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBox_Pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(Button_PesanKamar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Field_CariNamaNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_CariNamaNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_CariNamaNOActionPerformed

    private void Button_CariTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CariTamuActionPerformed
        String namaKontakTamu = Field_CariNamaNO.getText();
        int locTamu = tamuKontrol.cariTamu(namaKontakTamu);
        
        //JIka tidak ketemu -1
        if(locTamu == -1){
            Label_NamaTamu.setForeground(Color.RED);
            Label_NamaTamu.setText("Tamu tidak tersedia");
        }else{
            tamu = tamuKontrol.listTamu().get(locTamu);
            
            Label_NamaTamu.setForeground(Color.BLACK);
            String nama = tamuKontrol.listTamu().get(locTamu).getNamaTamu();
            Label_NamaTamu.setText("<html>Ditemukan dengan nama <font color='green'>" + nama + "</font></html>");
        }
    }//GEN-LAST:event_Button_CariTamuActionPerformed

    private void Button_PilihKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PilihKamarActionPerformed
        if(List_KamarKosong.getSelectedValue() != null){
            String NoKamar = (String) List_KamarKosong.getSelectedValue();
            kamar = kamarKontrol.getKamar(NoKamar);
            Label_KamarTerpilih.setText("<html>Kamar <font color='green'>" + NoKamar + "</font> dipilih</html>");
        }else{
            Label_KamarTerpilih.setText("<html><font color='red'>Plih kamar terlebih dahulu</font></html>");
        }
    }//GEN-LAST:event_Button_PilihKamarActionPerformed

    private void List_KamarKosongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_KamarKosongMouseClicked
        String NoKamar = (String) List_KamarKosong.getSelectedValue();
        Kamar pilihKamar = kamarKontrol.getKamar(NoKamar);
        
        //Konverter
        String tipeKamar;
        if(pilihKamar.isTipeKamar() == true){
            tipeKamar = "Single bad";
        }else{
            tipeKamar = "Double bad";
        }
        Label_TipeKamar.setText(": " + tipeKamar);
        
        String statusWifi;
        if(pilihKamar.isStatusWifi() == true){
            statusWifi = "Ada";
        }else{
            statusWifi = "Tidak ada";
        }
        Label_StatusWifi.setText(": " + statusWifi);
        
        Label_Rating.setText(": " + String.valueOf(pilihKamar.getRating()));
        
        //Nampilin harga di label
        int hargaKamar = pemesananKontrol.HargaKamarKosong(tipeKamar, statusWifi, pilihKamar.getRating(), "2022-01-15", "2022-01-16");
        String uangString = NumberFormat.getCurrencyInstance(new Locale("id", "ID")).format(hargaKamar);
        Label_HargaPerMalam.setText(": " + uangString + "/malam");
    }//GEN-LAST:event_List_KamarKosongMouseClicked

    private void Button_HitungHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_HitungHargaActionPerformed
        //harus jalan kamar dan waktu terisi
        if(kamar != null && DatePicker_CheckIn.getDate() != null && DatePicker_CheckOut.getDate() != null){
            //Ambil waktu di JXDate
            Date rawCheckIn = DatePicker_CheckIn.getDate();
            Date rawCheckOut = DatePicker_CheckOut.getDate();
            
            //Ubah dari date ke string
            DateFormat DateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String checkIn = DateFormat.format(rawCheckIn);
            String checkOut = DateFormat.format(rawCheckOut);
            
            //Konverter
            String tipeKamar;
            if(kamar.isTipeKamar() == true){
                tipeKamar = "Single bad";
            }else{
                tipeKamar = "Double bad";
            }

            String statusWifi;
            if(kamar.isStatusWifi() == true){
                statusWifi = "Ada";
            }else{
                statusWifi = "Tidak ada";
            }
            
            //Nampilin harga
            int hargaKamar = pemesananKontrol.HargaKamarKosong(tipeKamar, statusWifi, kamar.getRating(), checkIn, checkOut);
            String uangString = NumberFormat.getCurrencyInstance(new Locale("id", "ID")).format(hargaKamar);
            Label_Harga.setText("<html>Harga total: <font color='green'>" + uangString + "</font></html>");
        }
        
        //jika kamar dan waktu kosong
        if (kamar == null){
            Label_KamarTerpilih.setText("<html><font color='red'>Plih kamar terlebih dahulu</font></html>");
        }
        if(DatePicker_CheckIn.getDate() == null || DatePicker_CheckOut.getDate() == null){
            Label_Harga.setText("<html><font color='red'>Set waktu penginapan terlebih dahulu</font></html>");
        }
        
    }//GEN-LAST:event_Button_HitungHargaActionPerformed

    private void Button_PesanKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PesanKamarActionPerformed
        //Jika terisi tamu, kamar, dan waktu
        if(tamu == null){
            Label_NamaTamu.setText("<html><font color='red'>Cari tamu terlebih dahulu</font></html>");
        } 
        if (kamar == null){
            Label_KamarTerpilih.setText("<html><font color='red'>Plih kamar terlebih dahulu</font></html>");
        }
        if(DatePicker_CheckIn.getDate() == null || DatePicker_CheckOut.getDate() == null){
            Label_Harga.setText("<html><font color='red'>Set waktu penginapan terlebih dahulu</font></html>");
        }
        
        //Jika terisi semua baru jalanin
        if(tamu != null && kamar != null && DatePicker_CheckIn.getDate() != null && DatePicker_CheckOut.getDate() != null){
            //Ambil date di JXDate
            Date rawCheckIn = DatePicker_CheckIn.getDate();
            Date rawCheckOut = DatePicker_CheckOut.getDate();
            
            //Konver dari date ke string
            DateFormat DateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String checkIn = DateFormat.format(rawCheckIn);
            String checkOut = DateFormat.format(rawCheckOut);
            
            //konverter
            Boolean pembayaran;
            if(ComboBox_Pembayaran.getSelectedItem().equals("Cash")){
                pembayaran = true;
            }else{
                pembayaran = false;
            }
            
            String tipeKamar;
            if(kamar.isTipeKamar() == true){
                tipeKamar = "Single bad";
            }else{
                tipeKamar = "Double bad";
            }

            String statusWifi;
            if(kamar.isStatusWifi() == true){
                statusWifi = "Ada";
            }else{
                statusWifi = "Tidak ada";
            }
            
            //Buat pesanan
            int HargaKamar = pemesananKontrol.HargaKamarKosong(tipeKamar, statusWifi, kamar.getRating(), checkIn, checkOut);
            pemesananKontrol.updateListPemesanan(idxRow, tamu, pembayaran, checkIn, checkOut, kamar, HargaKamar);
            
            //update status menjadi terisi
            int locPemesananUpdate = kamarKontrol.getLoc(kamar);
            kamarKontrol.updateStatusKamar(locPemesananUpdate, true);
            
            //Update database
            try {
                database.simpanDatabase();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(PopupTambahEditTamu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(PopupTambahEditTamu.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            //close popup
            dispose();
        }
    }//GEN-LAST:event_Button_PesanKamarActionPerformed

    private void DatePicker_CheckOutPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_DatePicker_CheckOutPopupMenuWillBecomeVisible
        //jika checkIn terisi
        if(DatePicker_CheckIn.getDate() != null){
            //convert date ke besok hari
            int MILLIS_IN_A_DAY = 1000 * 60 * 60 * 24;
            Date besok = new Date(DatePicker_CheckIn.getDate().getTime() + MILLIS_IN_A_DAY);

            DatePicker_CheckOut.getMonthView().setLowerBound(besok);
        }
    }//GEN-LAST:event_DatePicker_CheckOutPopupMenuWillBecomeVisible

    private void DatePicker_CheckInPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_DatePicker_CheckInPopupMenuWillBecomeVisible
        //jika checkOut terisi
        if(DatePicker_CheckOut.getDate() != null){
            //convert date ke besok hari
            int MILLIS_IN_A_DAY = 1000 * 60 * 60 * 24;
            Date Kemarin = new Date(DatePicker_CheckOut.getDate().getTime() - MILLIS_IN_A_DAY);

            DatePicker_CheckIn.getMonthView().setUpperBound(Kemarin);
        }
    }//GEN-LAST:event_DatePicker_CheckInPopupMenuWillBecomeVisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupTambahEditPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupTambahEditPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupTambahEditPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupTambahEditPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PopupTambahEditPemesanan dialog = new PopupTambahEditPemesanan(new javax.swing.JFrame(), true, -1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_CariTamu;
    private javax.swing.JButton Button_HitungHarga;
    private javax.swing.JButton Button_PesanKamar;
    private javax.swing.JButton Button_PilihKamar;
    private javax.swing.JComboBox<String> ComboBox_Pembayaran;
    private org.jdesktop.swingx.JXDatePicker DatePicker_CheckIn;
    private org.jdesktop.swingx.JXDatePicker DatePicker_CheckOut;
    private javax.swing.JTextField Field_CariNamaNO;
    private javax.swing.JLabel Label_Harga;
    private javax.swing.JLabel Label_HargaPerMalam;
    private javax.swing.JLabel Label_KamarTerpilih;
    private javax.swing.JLabel Label_NamaTamu;
    private javax.swing.JLabel Label_Rating;
    private javax.swing.JLabel Label_StatusWifi;
    private javax.swing.JLabel Label_TipeKamar;
    private javax.swing.JList<String> List_KamarKosong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
