/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PopupMenu;

import Database.DriverDatabase;
import Entitas.Kamar;
import Kontrol.KamarKontrol;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class PopupTambahEditKamar extends javax.swing.JDialog {
    private DriverDatabase database;
    
    private KamarKontrol kamarKontrol;
    
    private int idxRow;
    
    private void loadDatabase() throws IOException{
        database = new DriverDatabase();
        database.memuatDatabase();
        
        kamarKontrol = database.getKamarKontrol();
    }
    
    private void setFieldEdit(){
        Kamar kamarIdx = kamarKontrol.listKamar().get(idxRow);
        
        //isi field no kamar
        Field_Nomor_Kamar.setText(kamarIdx.getNomorKamar());
        
        //isi combobox tipe kamar
        Object obj_tipeKamar;
        if(kamarIdx.isTipeKamar() == true){
            String s = "Single bed";  
            obj_tipeKamar = s;
        }else{
            String s = "Double bed";  
            obj_tipeKamar = s;
        }
        CBox_Tipe_Kamar.setSelectedItem(obj_tipeKamar);
        
        //isi combobox status wifi
        Object obj_statusWifi;
        if(kamarIdx.isStatusWifi() == true){
            String s = "Ada";  
            obj_statusWifi = s;
        }else{
            String s = "Tidak Ada";  
            obj_statusWifi = s;
        }
        CBox_Status_Wifi.setSelectedItem(obj_statusWifi);
        
        //isi combobox status kamar
        Object obj_statusKamar;
        if(kamarIdx.isStatusKamar() == true){
            String s = "Ditempati";  
            obj_statusKamar = s;
        }else{
            String s = "Kosong";  
            obj_statusKamar = s;
        }
        CBox_Status_Kamar.setSelectedItem(obj_statusKamar);
        
        //isi fieldTipeKamar
        Field_Rating.setText(String.valueOf(kamarIdx.getRating()));
    }

    /**
     * Creates new form PopupTambahEditKamar
     */
    public PopupTambahEditKamar(java.awt.Frame parent, boolean modal, int idxRow) {
        super(parent, modal);
        try {
            loadDatabase();
        } catch (IOException ex) {
            Logger.getLogger(PopupTambahEditTamu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Set id row menjadi variabel global
        this.idxRow = idxRow;
        
        initComponents();
        
        if(idxRow != -1){
            setFieldEdit();
            Button_Tambah_kamar.setText("Update kamar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CBox_Tipe_Kamar = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        CBox_Status_Wifi = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        CBox_Status_Kamar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Field_Rating = new javax.swing.JTextField();
        Button_Tambah_kamar = new javax.swing.JButton();
        Label_Nomor_Kamar = new javax.swing.JLabel();
        Field_Nomor_Kamar = new javax.swing.JTextField();
        Label_Validation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tipe kamar");

        CBox_Tipe_Kamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single bed", "Double bed" }));

        jLabel2.setText("Status Wi-Fi");

        CBox_Status_Wifi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ada Wi-Fi", "Tidak ada Wi-Fi" }));

        jLabel3.setText("Status kamar");

        CBox_Status_Kamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ditempati", "Kosong" }));

        jLabel4.setText("Rating");

        Field_Rating.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Field_RatingKeyTyped(evt);
            }
        });

        Button_Tambah_kamar.setText("Tambah Kamar");
        Button_Tambah_kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Tambah_kamarActionPerformed(evt);
            }
        });

        Label_Nomor_Kamar.setText("Nomor kamar");

        Field_Nomor_Kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_Nomor_KamarActionPerformed(evt);
            }
        });
        Field_Nomor_Kamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Field_Nomor_KamarKeyTyped(evt);
            }
        });

        Label_Validation.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBox_Tipe_Kamar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 272, Short.MAX_VALUE))
                    .addComponent(CBox_Status_Wifi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CBox_Status_Kamar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Field_Rating)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button_Tambah_kamar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Nomor_Kamar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Field_Nomor_Kamar)
                    .addComponent(Label_Validation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Nomor_Kamar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field_Nomor_Kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBox_Tipe_Kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBox_Status_Wifi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBox_Status_Kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field_Rating, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_Validation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(Button_Tambah_kamar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Tambah_kamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Tambah_kamarActionPerformed
        String inNomorKamar = Field_Nomor_Kamar.getText();
        String cekRatings = Field_Rating.getText();
        if(inNomorKamar.equals("") || cekRatings.equals("")){ //Jika field masing kososng 
            Label_Validation.setText("<html><font color=red>Inputkan semua data dahulu</font></html>");  
        } else {
            String cekTipeKamar = (String) CBox_Tipe_Kamar.getSelectedItem();
            String cekStatusWifi = (String) CBox_Status_Wifi.getSelectedItem();
            String cekStatusKamar = (String) CBox_Status_Kamar.getSelectedItem();
            int inRating = Integer.parseInt(Field_Rating.getText());
            //converter
            boolean inTipeKamar = false;
            if(cekTipeKamar.equals("Single bed")){
                inTipeKamar = true;
            }else if(cekTipeKamar.equals("Double bed")){
                inTipeKamar = false;
            }

            boolean inStatusWifi = false;
            if(cekStatusWifi.equals("Ada Wi-Fi")){
                inStatusWifi = true;
            }else if(cekStatusWifi.equals("Tidak ada Wi-Fi")){
                inStatusWifi = false;
            }

            boolean inStatusKamar = false;
            if(cekStatusKamar.equals("Ditampati")){
                inStatusKamar = true;
            }else if(cekStatusKamar.equals("Kosong")){
                inStatusKamar = false;
            }
            //Buat Kamar
            kamarKontrol.updateListKamar(idxRow, inNomorKamar, inTipeKamar, inStatusWifi, inStatusKamar, inRating);
            /*
            //Update Kamar
            int locKamarUpdate = kamarKontrol.getLocFromKamar(kamar);
            kamarKontrol.updateStatusKamar(locKamarUpdate, true);
            */
            //update database
            try {
                database.simpanDatabase();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(PopupTambahEditKamar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(PopupTambahEditKamar.class.getName()).log(Level.SEVERE, null, ex);
            }
            //close popup
            dispose();
        }
    }//GEN-LAST:event_Button_Tambah_kamarActionPerformed

    private void Field_Nomor_KamarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Field_Nomor_KamarKeyTyped
        char s=evt.getKeyChar();
        if(!Character.isDigit(s)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_Field_Nomor_KamarKeyTyped

    private void Field_RatingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Field_RatingKeyTyped
        char s=evt.getKeyChar();
        if(!Character.isDigit(s)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_Field_RatingKeyTyped

    private void Field_Nomor_KamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_Nomor_KamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_Nomor_KamarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupTambahEditKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupTambahEditKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupTambahEditKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupTambahEditKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PopupTambahEditKamar dialog = new PopupTambahEditKamar(new javax.swing.JFrame(), true, -1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Tambah_kamar;
    private javax.swing.JComboBox<String> CBox_Status_Kamar;
    private javax.swing.JComboBox<String> CBox_Status_Wifi;
    private javax.swing.JComboBox<String> CBox_Tipe_Kamar;
    private javax.swing.JTextField Field_Nomor_Kamar;
    private javax.swing.JTextField Field_Rating;
    private javax.swing.JLabel Label_Nomor_Kamar;
    private javax.swing.JLabel Label_Validation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
