/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PopupMenu;

import Database.Database;
import Entitas.Tamu;
import Kontrol.TamuKontrol;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class PopupTambahEditTamu extends javax.swing.JDialog implements PopupMenu{
    private Database database;
    
    private TamuKontrol tamuKontrol;
    
    private int idxRow;
    
    public void loadDatabase() throws IOException{
        database = new Database();
        database.memuatDatabase();
        
        tamuKontrol = database.getTamuKontrol();
    }
    
    public void setFieldEdit(){
       Tamu tamuidx = tamuKontrol.listTamu().get(idxRow);
       
       
       String inNamaTamu = tamuidx.getNamaTamu();
       String inNomorKartuKredit = tamuidx.getNomorKartuKredit();
       String inAlamat = tamuidx.getAlamat();
       String inNegara = tamuidx.getNegara();
       String inGender = tamuidx.getGender();
       String inKontak = tamuidx.getKontak();
       
       Field_KartuKredit.setText(inNomorKartuKredit);
       Field_Nama.setText(inNamaTamu);
       TextField_NoTlp.setText(inKontak);
       Field_Alamat.setText(inAlamat);
       ComboBox_Negara.setSelectedItem(inNegara);
       ComboBox_Gender.setSelectedItem(inGender);
    }

    /**
     * Creates new form PopupTambahEditTamu
     */
    public PopupTambahEditTamu(java.awt.Frame parent, boolean modal, int idxRow) {
        super(parent, modal);
        try {
            loadDatabase();
        } catch (IOException ex) {
            Logger.getLogger(PopupTambahEditTamu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Set id row menjadi variabel global
        this.idxRow = idxRow;
        
        initComponents();
        
        if(idxRow != -1){
            setFieldEdit();
            Button_TambahTamu.setText("Update tamu");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Field_Nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Field_KartuKredit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Field_Alamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ComboBox_Gender = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        TextField_NoTlp = new javax.swing.JTextField();
        Button_TambahTamu = new javax.swing.JButton();
        ComboBox_Negara = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nama");

        Field_Nama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Field_NamaMouseClicked(evt);
            }
        });
        Field_Nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Field_NamaKeyTyped(evt);
            }
        });

        jLabel2.setText("Nomor kartu kredit");

        Field_KartuKredit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Field_KartuKreditMouseClicked(evt);
            }
        });
        Field_KartuKredit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Field_KartuKreditKeyTyped(evt);
            }
        });

        jLabel3.setText("Alamat");

        Field_Alamat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Field_AlamatMouseClicked(evt);
            }
        });

        jLabel4.setText("Negara");

        jLabel5.setText("Jenis kelamin");

        ComboBox_Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        jLabel6.setText("Nomor telepon");

        TextField_NoTlp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextField_NoTlpMouseClicked(evt);
            }
        });
        TextField_NoTlp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_NoTlpKeyTyped(evt);
            }
        });

        Button_TambahTamu.setText("Tambah Tamu");
        Button_TambahTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TambahTamuActionPerformed(evt);
            }
        });

        ComboBox_Negara.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan", "Brazil", "China", "Denmark", "Egypt, Arab Rep.", "Finland", "Germany", "Hong Kong SAR, China", "Indonesia", "Japan", "Korea, Rep.", "Libya", "Mexico", "Nigeria", "Oman", "Portugal", "Qatar", "Romania", "Singapore", "Thailand", "United States", "Vietnam", "West Bank and Gaza", "Yemen, Rep.", "Zimbabwe" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button_TambahTamu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Field_Nama)
                    .addComponent(Field_KartuKredit)
                    .addComponent(ComboBox_Negara, 0, 348, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Field_Alamat)
                    .addComponent(ComboBox_Gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextField_NoTlp))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field_KartuKredit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBox_Negara, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBox_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_NoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(Button_TambahTamu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_TambahTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TambahTamuActionPerformed
        String inAlamat = Field_Alamat.getText();
        String inNomorKartuKredit = Field_KartuKredit.getText();
        String inNamaTamu = Field_Nama.getText();
        String inKontak = TextField_NoTlp.getText();
        String inNegara = (String) ComboBox_Negara.getSelectedItem();
        String inGender = (String) ComboBox_Gender.getSelectedItem();
        int val = tamuKontrol.cariTamu(inNamaTamu);
        if(inNamaTamu.equals("")){
            Field_Nama.setForeground (Color.red);
            Field_Nama.setText("Nama tidak boleh kosong"); 
        }else{
            if(val != -1 && idxRow == -1){    
                Field_Nama.setForeground (Color.red);
                Field_Nama.setText("Harap ganti nama");   
            }
        }
        if(inAlamat.equals("")){
            Field_Alamat.setForeground (Color.red);
            Field_Alamat.setText("Harap ganti nama");
        }
        if(inKontak.length()!=12){
            getToolkit().beep();
            setVisible(true);
            TextField_NoTlp.setForeground (Color.red);
            TextField_NoTlp.setText("Agar valid, isi 12 digit");
            
        }
        if(inNomorKartuKredit.length() != 16){
            getToolkit().beep();
            setVisible(true);
            Field_KartuKredit.setForeground (Color.red);
            Field_KartuKredit.setText("Agar valid, isi 16 digit");
            
        }
        if((val == -1 || idxRow != -1) && inKontak.length()==12 && inNomorKartuKredit.length() == 16 && !Field_Alamat.equals("")) {
            tamuKontrol.updateListTamu(idxRow,inNamaTamu, inNomorKartuKredit, inAlamat, inNegara, inGender, inKontak);
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "masukkan data yang valid","ERROR", JOptionPane.ERROR_MESSAGE);
        }

        try {
            database.simpanDatabase();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PopupTambahEditTamu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(PopupTambahEditTamu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Button_TambahTamuActionPerformed

    private void Field_NamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Field_NamaKeyTyped
        Field_Nama.setForeground (Color.BLACK);
        char s=evt.getKeyChar();
        if(Character.isDigit(s)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_Field_NamaKeyTyped

    private void Field_KartuKreditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Field_KartuKreditKeyTyped
        Field_KartuKredit.setForeground (Color.BLACK);
        char s=evt.getKeyChar();
        if(!Character.isDigit(s)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_Field_KartuKreditKeyTyped

    private void TextField_NoTlpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_NoTlpKeyTyped
        TextField_NoTlp.setForeground (Color.BLACK);
        char s=evt.getKeyChar();
        if(!Character.isDigit(s)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TextField_NoTlpKeyTyped

    private void Field_NamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Field_NamaMouseClicked
        Field_Nama.setForeground (Color.BLACK);
    }//GEN-LAST:event_Field_NamaMouseClicked

    private void Field_KartuKreditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Field_KartuKreditMouseClicked
        Field_KartuKredit.setForeground (Color.BLACK);
    }//GEN-LAST:event_Field_KartuKreditMouseClicked

    private void TextField_NoTlpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextField_NoTlpMouseClicked
        TextField_NoTlp.setForeground (Color.BLACK);
    }//GEN-LAST:event_TextField_NoTlpMouseClicked

    private void Field_AlamatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Field_AlamatMouseClicked
        Field_Alamat.setForeground (Color.BLACK);
    }//GEN-LAST:event_Field_AlamatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupTambahEditTamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupTambahEditTamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupTambahEditTamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupTambahEditTamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PopupTambahEditTamu dialog = new PopupTambahEditTamu(new javax.swing.JFrame(), true, -1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_TambahTamu;
    private javax.swing.JComboBox<String> ComboBox_Gender;
    private javax.swing.JComboBox<String> ComboBox_Negara;
    private javax.swing.JTextField Field_Alamat;
    private javax.swing.JTextField Field_KartuKredit;
    private javax.swing.JTextField Field_Nama;
    private javax.swing.JTextField TextField_NoTlp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
