/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

/**
 *
 * @author aryap
 */
public class Login extends javax.swing.JFrame {
    private String username;
    private String password;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        Label_Judul = new javax.swing.JLabel();
        Label_Username = new javax.swing.JLabel();
        Field_Username = new javax.swing.JTextField();
        Label_Password = new javax.swing.JLabel();
        Field_Password = new javax.swing.JPasswordField();
        Label_LoginGagal = new javax.swing.JLabel();
        Button_Login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        Label_Judul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Label_Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Judul.setText("Pemesanan Kamar Hotel");

        Label_Username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label_Username.setText("Username");

        Field_Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Field_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_UsernameActionPerformed(evt);
            }
        });

        Label_Password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label_Password.setText("Password");

        Field_Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Field_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_PasswordActionPerformed(evt);
            }
        });

        Label_LoginGagal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label_LoginGagal.setForeground(new java.awt.Color(255, 51, 51));

        Button_Login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button_Login.setText("Login");
        Button_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_LoginGagal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Button_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Field_Password, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Field_Username)
                    .addComponent(Label_Judul, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Password)
                            .addComponent(Label_Username))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(Label_Judul)
                .addGap(18, 18, 18)
                .addComponent(Label_Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_LoginGagal)
                .addGap(18, 18, 18)
                .addComponent(Button_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Field_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_UsernameActionPerformed

    private void Button_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LoginActionPerformed
        username = "admin";
        password = "admin";
        
        String inUsername =  Field_Username.getText();//password
        String inPassword = Field_Password.getText();//username
        
        if(inUsername.equals(username) && inPassword.equals(password)){
            new MainMenu().setVisible(true);
            dispose();
        } else {
            Field_Username.setText(null);
            Field_Password.setText(null);
            Label_LoginGagal.setText("Login gagal");
        }
    }//GEN-LAST:event_Button_LoginActionPerformed

    private void Field_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Login;
    private javax.swing.JPasswordField Field_Password;
    private javax.swing.JTextField Field_Username;
    private javax.swing.JLabel Label_Judul;
    private javax.swing.JLabel Label_LoginGagal;
    private javax.swing.JLabel Label_Password;
    private javax.swing.JLabel Label_Username;
    private javax.swing.Box.Filler filler1;
    // End of variables declaration//GEN-END:variables
}
