/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

import PopupMenu.PopupTambahEditPemesanan;
import Database.DriverDatabase;
import Kontrol.KamarKontrol;
import Kontrol.PemesananKontrol;
import Kontrol.TamuKontrol;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aryap
 */
public class PemesananMenu extends javax.swing.JFrame {
    private DriverDatabase database;

    private PemesananKontrol pemesananKontrol;
    private TamuKontrol tamuKontrol;
    private KamarKontrol kamarKontrol;
    
    private DefaultTableModel model_Pemesanan;
    
    private void loadDatabase() throws IOException{
        database = new DriverDatabase();
        database.memuatDatabase();
        
        pemesananKontrol = database.getPemesananKontrol();
        tamuKontrol = database.getTamuKontrol();
        kamarKontrol = database.getKamarKontrol();
    }
    
    private void setTable(){
        try {
            loadDatabase();
        } catch (IOException ex) {
            Logger.getLogger(PemesananMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Pemesanan
        model_Pemesanan = (DefaultTableModel) Table_Pemesanan.getModel();
        model_Pemesanan.setRowCount(0);
        for (int i = 0; i < pemesananKontrol.sizeData(); i++) {
            model_Pemesanan.addRow(pemesananKontrol.oneRow(i));
        }
    }
    /**
     * Creates new form PemesananMenu
     */
    public PemesananMenu() {
        initComponents();
        setTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_JudulPemesanan = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_Pemesanan = new javax.swing.JTable();
        Button_TambahPemesanan = new javax.swing.JButton();
        Button_EditPemesanan = new javax.swing.JButton();
        Button_HapusPemesanan = new javax.swing.JButton();
        Button_Kembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_JudulPemesanan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label_JudulPemesanan.setText("Data Pemesanan");

        Table_Pemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode pemesanan", "Pemesan", "Nomor kamar", "Check in", "Check out", "Pembayaran", "Dibayarkan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Pemesanan.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(Table_Pemesanan);

        Button_TambahPemesanan.setText("Tambah");
        Button_TambahPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TambahPemesananActionPerformed(evt);
            }
        });

        Button_EditPemesanan.setText("Edit");
        Button_EditPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EditPemesananActionPerformed(evt);
            }
        });

        Button_HapusPemesanan.setText("Hapus");
        Button_HapusPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_HapusPemesananActionPerformed(evt);
            }
        });

        Button_Kembali.setText("Kembali");
        Button_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_KembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button_TambahPemesanan)
                        .addGap(18, 18, 18)
                        .addComponent(Button_EditPemesanan)
                        .addGap(18, 18, 18)
                        .addComponent(Button_HapusPemesanan)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Button_Kembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Label_JudulPemesanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Label_JudulPemesanan)
                        .addComponent(Button_Kembali))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_TambahPemesanan)
                    .addComponent(Button_EditPemesanan)
                    .addComponent(Button_HapusPemesanan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_TambahPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TambahPemesananActionPerformed
        PopupTambahEditPemesanan tambah_Pemesanan = new PopupTambahEditPemesanan(null,true, -1);
        tambah_Pemesanan.setVisible(true);
        setTable();
    }//GEN-LAST:event_Button_TambahPemesananActionPerformed

    private void Button_EditPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EditPemesananActionPerformed
        if(Table_Pemesanan.getSelectedRow() != -1){
            PopupTambahEditPemesanan tambah_Pemesanan = new PopupTambahEditPemesanan(null,true, Table_Pemesanan.getSelectedRow());
            tambah_Pemesanan.setVisible(true);
            setTable();
        }
    }//GEN-LAST:event_Button_EditPemesananActionPerformed

    private void Button_HapusPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_HapusPemesananActionPerformed
        if(Table_Pemesanan.getSelectedRow() != -1){
            //update status menjadi kosong
            int locPemesananUpdate = kamarKontrol.getLocFromKamar(pemesananKontrol.listPemesanan().get(Table_Pemesanan.getSelectedRow()).getKamar());
            kamarKontrol.updateStatusKamar(locPemesananUpdate, false);

            //Hapus pesanan
            pemesananKontrol.listPemesanan().remove(Table_Pemesanan.getSelectedRow());

            //Update database
            try {
                database.simpanDatabase();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(PemesananMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(PemesananMenu.class.getName()).log(Level.SEVERE, null, ex);
            }

            setTable();
        }
    }//GEN-LAST:event_Button_HapusPemesananActionPerformed

    private void Button_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_KembaliActionPerformed
        new MainMenu().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_Button_KembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PemesananMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PemesananMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PemesananMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PemesananMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PemesananMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_EditPemesanan;
    private javax.swing.JButton Button_HapusPemesanan;
    private javax.swing.JButton Button_Kembali;
    private javax.swing.JButton Button_TambahPemesanan;
    private javax.swing.JLabel Label_JudulPemesanan;
    private javax.swing.JTable Table_Pemesanan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
