/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

import PopupMenu.PopupTambahEditTamu;
import Database.DriverDatabase;
import Kontrol.KamarKontrol;
import Kontrol.PemesananKontrol;
import Kontrol.TamuKontrol;
import PopupMenu.PopupTambahEditKamar;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aryap
 */
public class TamuMenu extends javax.swing.JFrame {
    private DriverDatabase database;

    private TamuKontrol tamuKontrol;
    
    private DefaultTableModel model_Tamu;
    
    private void loadDatabase() throws IOException{
        database = new DriverDatabase();
        database.memuatDatabase();
        
        tamuKontrol = database.getTamuKontrol();
    }
    
    private void setTable(){
        try {
            loadDatabase();
        } catch (IOException ex) {
            Logger.getLogger(TamuMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Tamu
        model_Tamu = (DefaultTableModel) Table_Tamu.getModel();
        model_Tamu.setRowCount(0);
        for (int i = 0; i < tamuKontrol.sizeData(); i++) {
            model_Tamu.addRow(tamuKontrol.oneRow(i));
        }
    }
    /**
     * Creates new form TamuMenu
     */
    public TamuMenu() {
        initComponents();
        setTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Tamu = new javax.swing.JTable();
        Button_TambahTamu = new javax.swing.JButton();
        Button_EditTamu = new javax.swing.JButton();
        Button_HapusKamar = new javax.swing.JButton();
        Button_Kembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Data Tamu");

        Table_Tamu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nama", "Kartu kredit", "Alamat", "Negara", "Jenis kelamin", "Nomor telepon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Tamu.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Table_Tamu);

        Button_TambahTamu.setText("Tambah");
        Button_TambahTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TambahTamuActionPerformed(evt);
            }
        });

        Button_EditTamu.setText("Edit");
        Button_EditTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EditTamuActionPerformed(evt);
            }
        });

        Button_HapusKamar.setText("Hapus");
        Button_HapusKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_HapusKamarActionPerformed(evt);
            }
        });

        Button_Kembali.setText("Kembali");
        Button_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_KembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button_TambahTamu)
                        .addGap(18, 18, 18)
                        .addComponent(Button_EditTamu)
                        .addGap(18, 18, 18)
                        .addComponent(Button_HapusKamar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_Kembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button_Kembali)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_TambahTamu)
                    .addComponent(Button_EditTamu)
                    .addComponent(Button_HapusKamar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_TambahTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TambahTamuActionPerformed
        PopupTambahEditTamu tambah_Tamu = new PopupTambahEditTamu(null,true, -1);
        tambah_Tamu.setVisible(true);
        setTable();
    }//GEN-LAST:event_Button_TambahTamuActionPerformed

    private void Button_HapusKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_HapusKamarActionPerformed
        if(Table_Tamu.getSelectedRow() != -1){
            //Hapus kamar
            tamuKontrol.listTamu().remove(Table_Tamu.getSelectedRow());

            //Update database
            try {
                database.simpanDatabase();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(TamuMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(TamuMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        setTable();
    }//GEN-LAST:event_Button_HapusKamarActionPerformed

    private void Button_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_KembaliActionPerformed
        new MainMenu().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_Button_KembaliActionPerformed

    private void Button_EditTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EditTamuActionPerformed
        if(Table_Tamu.getSelectedRow() != -1){
            PopupTambahEditTamu tambahTamu = new PopupTambahEditTamu(null,true, Table_Tamu.getSelectedRow());
            tambahTamu.setVisible(true);
            setTable();
        }
    }//GEN-LAST:event_Button_EditTamuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TamuMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TamuMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TamuMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TamuMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TamuMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_EditTamu;
    private javax.swing.JButton Button_HapusKamar;
    private javax.swing.JButton Button_Kembali;
    private javax.swing.JButton Button_TambahTamu;
    private javax.swing.JTable Table_Tamu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
